/*
 * This file is generated by jOOQ.
 */
package database;


import database.tables.ConnectionPoolTest;


/**
 * Convenience access to all tables in connectionpool.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>connectionpool.connection_pool_test</code>.
     */
    public static final ConnectionPoolTest CONNECTION_POOL_TEST = ConnectionPoolTest.CONNECTION_POOL_TEST;
}
